### ISSUE TITLE
Specifying 'None' to scanpy-find-variable-genes.py for n_top_genes

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/scanpy-scripts#30]
Hi @nh3 ,

I'd like to be able to specify the defaults for all the scripts of scanpy-scripts (so that I can set them in a config file for later tweaking).

The variable genes script states 'None' for a default:

```
  -n N_TOP_GENES, --n-top-genes N_TOP_GENES
                        Number of highly variable genes to keep, ignoring
                        --subset-parameters when set. Default: None
```

 But if I specify 'None' to the above option I get:

```
scanpy-find-variable-genes.py: error: argument -n/--n-top-genes: invalid int value: 'None'
```

What would you suggest?

**Comment by pinin4fjords** [comment]
Never mind, I'll just do more translation from the config

**Comment by nh3** [comment]
What's happening here is that, `--n-top-genes` has a type of `int` and when a string `"None"` is supplied, argparse tries to convert it to `int` but in vain. Default values are for situation when the option is not specified by the user. In cases when the default value is of the same type as the specified type of the option, the user can supply that value. But when the default value is `None`, the only way to let it be `None` is to not specify it. In this case the default value is `None` rather than an integer because the underlying function requires and depends on it to know that the user has not supplied a value hence the code making use of this value is not executed.

**Comment by pinin4fjords** [comment]
Yes, thanks Ni, I understand that. It's just that making it impossible to specify the default behaviour explicitly creates a couple of problems when building workflows with these components.

Firstly it's just neater if you can compare two commands with the same number of arguments and immediately infer the behaviour, rather than having to work out what implicit behaviours have been triggered by missing arguments- but that's relatively trivial. 

Worse is the situation when I'm mapping between a config file and a workflow component. If I can't specify the default behaviour then I'm forced to insert logic that checks for a null config value (e.g. the string 'none' and remove the associated parameter accordingly. e.g. look how complicated my Nextflow call has to be to run PCA with flags (rather than true/ false specification or something): 

Config: https://github.com/ebi-gene-expression-group/scxa_worflows/blob/3b7b8f891a5b1f731d3266347ad97abcf6d3c812/conf/protocol/smart.conf#L76

Workflow component: https://github.com/ebi-gene-expression-group/scxa_worflows/blob/3b7b8f891a5b1f731d3266347ad97abcf6d3c812/scanpy.nf#L195

**Comment by pinin4fjords** [comment]
(thats a bit of work-in-progress by the way, don't look too hard for errors ;-) )

**Comment by nh3** [comment]
Firstly, this default value and the behaviour of using `None` to determine the path of execution is not my improvisation but the behaviour of the underlying scanpy function (https://scanpy.readthedocs.io/en/latest/api/scanpy.api.pp.filter_genes_dispersion.html).

Secondly, changing a programme's behaviour by presence/absence of an option has long been one of the conventions of command line tools both aged and modern. My feeling is that one would have to deal with that one way or another. Think about it, when the presence/absence of an option carries a meaning, shouldn't the whole thing (--option value) rather than just the value become a configurable variable? E.g. use `$n_top_genes` instead of `--n-top-genes $n_top_genes`. You see what I mean?

Finally, the links are not working, as `scxa_workflow` doesn't seem to be visible to me, so I can't evaluate the specific difficulty associated with your use case.

**Comment by pinin4fjords** [comment]
Yep, don't worry, I'm not expecting you to do anything about this necessarily (I did close the issue), may just be a difference of perspective, just raising the point. I've added you  as collaborator on the project so you can see what I mean. 

I'm aware of the conventions, it's just that we built these scripts as workflow components, so it seems they should work optimally for that use case. 

I'm not keen on putting sections of a tool's command-line syntax into the config. It makes it messy, hard to read and harder to transfer to other methods.

**Comment by nh3** [comment]
Thanks for sharing the repository. That's exactly the use case I imagined. Well, from my perspective anything except the executable is configuration. And to me hardcoding the switches in the scripts makes it susceptible to changes in CLI interface. I'd rather organise those things in config such that each variable represents a semantic units (can even encompass several options if they meant to go together) that expresses a modification of the executable's behaviour. This way you have an abstracted script that focuses on logic between commands and a config that focuses on parameterising the commands that is easy to maintain and transferable. Just my two cents.

BTW, 'NULL' is not interpreted as `NULL` by optparse in R, so unless you hardcode the NULL -> `NULL` conversion, which the user wouldn't know without seeing the code, the only way to specify it is to skip it, as in the case of scater-plot-reduced-dim.R and others. And I am pretty sure you will encounter many commands that wouldn't to that conversion.

**Comment by pinin4fjords** [comment]
Oh yes, I fully accept the issue may be present in our other scripts repos. This is just the first time I've tried to compile a production pipeline using them, so the issues are occurring to me.

**Comment by nh3** [comment]
This is not about specific scripts but a demonstration that it is the expected behaviour of a wide range of CLI tools and command line parsers, so, alas, the workflow has to deal with that.
