### ISSUE TITLE
0.0.5: read_10x var names not being picked up

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/scanpy-scripts#46]
Even though `-v gene_ids` is set, the resulting anndata object is in `gene_symbols` mode:

![image](https://user-images.githubusercontent.com/368478/61010012-95691c80-a36c-11e9-91b8-87537e435891.png)

this produces that our gene symbols on the second column of the genes files don't get incorporated in the anndata object, losing gene symbols.

**Comment by nh3** [comment]
`-v gene_ids` means the 1st column "gene_ids" is used as index for the var table, leaving "gene_symbols" as the only column. If `-v gene_symbols` is given, the 2nd column "gene_symbols" is used as index and leaving "gene_ids" as the only column. This is the expected behaviour. No information is lost.
